Models/ErrorViewModel.cs
namespace AvaliacaoLp3_Shopping.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ViewModels/LojaViewModel.cs
namespace AvaliacaoLp3_Shopping.ViewModels;

public class LojaViewModel
{
    public int Id { get; set; }
    public int Piso { get; set; }
    public string Nome { get; set; }
    public string Descrição { get; set; }
    public string Tipo { get; set; }
    public string Email { get; set; }

    public LojaViewModel(int id, int piso, string nome, string descrição, string tipo, string email)
    {
        Id = id;
        Piso = piso;
        Nome = nome;
        Descrição = descrição;
        Tipo = tipo;
        Email = email;
    }


}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AvaliacaoLp3_Shopping.Models;

namespace AvaliacaoLp3_Shopping.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ShoppingController.cs
using Microsoft.AspNetCore.Mvc;
using AvaliacaoLp3_Shopping.Models;
using AvaliacaoLp3_Shopping.ViewModels;

namespace AvaliacaoLp3_Shopping.Controllers;

public class ShoppingController : Controller 
{
    //add lojas a lista, já que nao temos bdd 
    private static List<LojaViewModel> lojas = new List<LojaViewModel>();

    public IActionResult ListaLojKio() //lista do cliente
    {
        return View(lojas);
    }

    public IActionResult Gerenciamento() //lista do adm
    {
        return View(lojas);
    }

    //detalhe de cada loja
    public IActionResult Detalhe(int id){       

        //return View(lojas[id]);

        foreach(var loja in lojas)
        {
            if(loja.Id == id)
            {
               return View(loja);
            }
        }
        return View();
    }

/*alterações feitas depois da consulta em aula com o professor corrigindo as falhas de validação*/
    //cadastra loja
    public IActionResult Cadastro([FromForm] int id, [FromForm] string nome, [FromForm] string email, [FromForm] string tipo, [FromForm] string descricao, [FromForm] int piso){

        foreach (var loja in lojas)
        {

            if(loja.Nome.Equals(nome))
            {
                ViewData ["Nome"] = loja.Nome;
                return View("Mensagem");
            }
        }

        if(id != 0)
        { 
            lojas.Add(new LojaViewModel(id, piso, nome, descricao, tipo, email));
        } 

        return View() ;

    }


    //remove loja
    public IActionResult Remover(int id)
    {
        foreach(var loja in lojas)
        {
            if(loja.Id == id)
            {
               lojas.Remove(loja);
               ViewData ["Nome"] = loja.Nome;
               return View();
            }
        }

        return View();
    }


}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Avaliação LP3 - Shopping</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AvaliacaoLp3_Shopping.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Avaliação LP3 - Shopping</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shopping" asp-action="ListaLojKio">Listas de Lojas e Kiosques</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shopping" asp-action="Gerenciamento">Gerenciamento de lojas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AvaliacaoLp3_Shopping - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shopping/CadastrarLoja.cshtml
@{
    ViewData["Title"] = "Cadastro de lojas";
}

    <h1>Cadastre aqui a loja/kiosque:</h1>
    <hr>
    <form action="CadastrarLoja" method="post">

        <label for="nome">Nome</label>
        <input type="text" name="nome" id="nome" class="form-control" required>

        <label for="email">Email</label>
        <input type="email" name="email" id="email" class="form-control" required>


        <label for="piso">Piso</label>
            <select class="form-control form-control-sm" name="piso" id="piso" required>
                <option value="" disabled selected>Selecione o piso da loja</option>
                <option value="1">Piso 1</option>
                <option value="2">Piso 2</option>
                <option value="3">Piso 3</option>                        
            </select>


        <label for="piso">Tipo</label>
            <select class="form-control form-control-sm" name="tipo" id="tipo" required>
                <option value="" disabled selected> Selecione o tipo de estabelecimento:</option>
                <option value="Loja">Loja</option>
                <option value="Kiosque">Kiosque</option>
            </select>             

        <label for="descricao">Descrição</label>
        <textarea class="form-control" name="descricao" id="descricao" cols="30" rows="5"></textarea>

        <button type="submit">Enviar</button>
    </form>
</div>

Views/Shopping/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro de lojas";
}

    <h1>Cadastre aqui a loja/kiosque:</h1>
    <hr>
    <form action="Cadastro" method="post">


        <label for="id">Id</label>
        <input type="number" name="id" id="id" class="form-control" required>
        <label for="nome">Nome</label>
        <input type="text" name="nome" id="nome" class="form-control" required>

        <label for="email">Email</label>
        <input type="email" name="email" id="email" class="form-control" required>


        <label for="piso">Piso</label>
            <select class="form-control form-control-sm" name="piso" id="piso" required>
                <option value="" disabled selected>Selecione o piso da loja</option>
                <option value="1">Piso 1</option>
                <option value="2">Piso 2</option>
                <option value="3">Piso 3</option>                        
            </select>


        <label for="piso">Tipo</label>
            <select class="form-control form-control-sm" name="tipo" id="tipo" required>
                <option value="" disabled selected> Selecione o tipo de estabelecimento:</option>
                <option value="Loja">Loja</option>
                <option value="Kiosque">Kiosque</option>
            </select>             

        <label for="descricao">Descrição</label>
        <textarea class="form-control" name="descricao" id="descricao" cols="30" rows="5"></textarea>

        <button type="submit" id="cadastro">Cadastrar</button>
    </form>
</div>

Views/Shopping/Detalhe.cshtml
@{
    ViewData["Title"] = "Detalhes: ";
}

<h3>@Model.Nome</h3>
<hr>
<p>Id: @Model.Id</p>
<p>Piso: @Model.Piso</p>
<p>Tipo: @Model.Tipo</p>
<p>Descrição: @Model.Descrição</p>
<p>Email: @Model.Email</p>



<form action="/Shopping/Remover/@Model.Id">
    <button type="submit">Deletar</button>
</form>

Views/Shopping/Gerenciamento.cshtml
@model List<AvaliacaoLp3_Shopping.ViewModels.LojaViewModel>
@{
    ViewData["Title"] = "Administrador";
}


@if(Model.Count == 0) 
{
    <p>Nenhuma loja cadastrada</p>
    <form action="Cadastro">
            <button>Cadastrar loja</button>
    </form>
}
else 
{
    <h1>Lojas</h1>
    <p>@Model.Count lojas cadastradas</p>

    @*percorrendo e exibindo a lista*@
    @foreach(var loja in Model)
    {
       
        <h3>@loja.Nome</h3>
        <p>Piso: @loja.Piso</p>
        <a href="/Shopping/Detalhe/@loja.Id">
            <button>Detalhe</button>
        </a>
        
        <hr>

    }

}

Views/Shopping/ListaLojKio.cshtml
@model List<AvaliacaoLp3_Shopping.ViewModels.LojaViewModel>
@{
    ViewData["Title"] = "Lista de lojas e kiosques";
}


@if(Model.Count == 0) 
{
    <p>Nenhuma loja disponível.</p>
}
else 
{
    <h1>Lojas e Kiosques</h1>
    <p>@Model.Count lojas disponíveis:</p>

    @*percorrendo e exibindo a lista*@
    @foreach(var loja in Model)
    {
        <h2>@loja.Nome</h2>
        <p>Piso: @loja.Piso</p>
        <hr>
    }
}

Views/Shopping/Mensagem.cshtml
@{
    ViewData["Title"] = "Mensagem de erro ao cadastrar";
}

<div class="text-center">
    <h1>"@ViewData["Nome"]" já está cadastrada no sistema!</h1>
</div>

Views/Shopping/Remover.cshtml
@{
    ViewData["Title"] = "Mensagem ao usuário";
    var nome = ViewData["nome"];
}

<div class="text-center">
    <h1>Loja Deletada</h1>
</div>